### ISSUE TITLE
Error opening Stats screen after update today

### ISSUE THREAD

**Issue by Iris3Meow** [sivenchinniah/Pokemanki#10]
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-02 11:26:39

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1007, in onStats
  File "aqt\__init__.py", line 92, in open
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-48>", line 2, in __init__
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 521, in repl
  File "aqt\stats.py", line 52, in __init__
  File "aqt\stats.py", line 97, in refresh
  File "lib\site-packages\anki\stats.py", line 117, in report
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-30>", line 2, in todayStats_new
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\Savage Unicorn\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 38, in tagmonDisplay
    tagmon = TagPokemon()
  File "C:\Users\Savage Unicorn\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 214, in TagPokemon
    if config['generation_1']:
KeyError: 'generation_1'

Any idea why?

**Comment by cslayb** [comment]
I too was having this problem when I tried to add enabling just the gen 2 pokemon

**Comment by DoctorToBeIn23** [comment]
Not sure if this is the same error but I even tried to only have Pokemanki add on turned on and all others off but when I try to have pokemon by tags this is the error I got

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.4
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-04 20:24:26
Add-ons possibly involved: ⁨Pokemanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 175, in _statsLinkHandler
  File "aqt/main.py", line 1016, in onStats
  File "aqt/__init__.py", line 93, in open
  File "aqt/stats.py", line 52, in __init__
  File "aqt/stats.py", line 97, in refresh
  File "anki/stats.py", line 131, in report
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-2>", line 2, in easeGraph
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/633922407/tagmon.py", line 38, in tagmonDisplay
    tagmon = TagPokemon()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/633922407/tagmon.py", line 214, in TagPokemon
    if config['generation_1']:
KeyError: 'generation_1'

**Comment by AnkiUser123** [comment]
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Pokemanki

Error in sys.excepthook:
Traceback (most recent call last):
  File "aqt/errors.py", line 17, in excepthook
  File "aqt/errors.py", line 41, in write
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 902: ordinal not in range(128)

Original exception was:
Traceback (most recent call last):
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/toolbar.py", line 56, in _linkHandler
  File "aqt/toolbar.py", line 77, in _statsLinkHandler
  File "aqt/main.py", line 878, in onStats
  File "aqt/__init__.py", line 82, in open
  File "<decorator-gen-32>", line 2, in __init__
  File "anki/hooks.py", line 74, in decorator_wrapper
  File "anki/hooks.py", line 65, in repl
  File "aqt/stats.py", line 43, in __init__
  File "aqt/stats.py", line 85, in refresh
  File "anki/stats.py", line 117, in report
  File "<decorator-gen-10>", line 2, in todayStats
  File "anki/hooks.py", line 74, in decorator_wrapper
  File "anki/hooks.py", line 71, in repl
  File "/Users/hunter.stearns/Library/Application Support/Anki2/addons21/633922407/display.py", line 54, in pokemonDisplay
      File "/Users/hunter.stearns/Library/Application Support/Anki2/addons21/633922407/display.py", line 135, in _show
    if name == "Pikachu":
UnboundLocalError: local variable 'name' referenced before assignment

**Comment by AnkiUser123** [comment]
I also got an error message, did anyone figure out how to solve this?
