### ISSUE TITLE
Following generating the first Pokemon

### ISSUE THREAD

**Issue by yitzhakbg** [sivenchinniah/Pokemanki#12]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-02 21:46:06

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1007, in onStats
  File "aqt\__init__.py", line 92, in open
  File "aqt\stats.py", line 52, in __init__
  File "aqt\stats.py", line 97, in refresh
  File "lib\site-packages\anki\stats.py", line 117, in report
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-22>", line 2, in todayStats_new
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\yitzh\AppData\Roaming\Anki2\addons21\633922407\display.py", line 51, in pokemonDisplay
    result += _show(self,
  File "C:\Users\yitzh\AppData\Roaming\Anki2\addons21\633922407\display.py", line 149, in _show
    <td height = 300 width = 300 align = center><img src="/pokemon_images/%s.png" title=%s></td>""") % (data[0] + special, self.col.decks.name(data[1])))
UnboundLocalError: local variable 'special' referenced before assignment

**Comment by yitzhakbg** [comment]
Maybe I can guess at what might be causing the problem. I maintain several user profiles, but the Pokeman data structure is global and the Pokemon deck structures don't jive.
But then maintaining structures for each user (I have several - profile for each student) might become exorbitantly heavy. It's already pretty heavy. What do you think?
I also reinstalled a few times. Maybe the deletion didn't entirely clean out the data store and the new installation wasn't clean.
I really don't know, just throwing out ideas.
![image](https://user-images.githubusercontent.com/14580/75731302-f11b5800-5cf7-11ea-91a8-4db3b19f8492.png)
