### ISSUE TITLE
Crash in "collection" stats

### ISSUE THREAD

**Issue by giacomoran** [sivenchinniah/Pokemanki#16]
Hi, first of all thanks for the add-on!

I installed it almost as a joke, but it really works surprisingly well for motivation.

I just updated the add-on, now when I go to the "collection" screen of the Stats I get the following error message:

```
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-03-04 12:04:14
Add-ons possibly involved: Pokemanki

Caught exception:
Traceback (most recent call last):
  File "aqt/stats.py", line 45, in <lambda>
  File "aqt/stats.py", line 91, in changeScope
  File "aqt/stats.py", line 97, in refresh
  File "anki/stats.py", line 117, in report
  File "</usr/local/share/anki/bin/decorator.pyc:decorator-gen-14>", line 2, in todayStats
  File "anki/hooks.py", line 530, in decorator_wrapper
  File "anki/hooks.py", line 527, in repl
  File "/home/giacomo/.local/share/Anki2/addons21/633922407/display.py", line 41, in pokemonDisplay
    multideckmon = MultiPokemon(*args, **kwargs)
  File "/home/giacomo/.local/share/Anki2/addons21/633922407/compute.py", line 671, in MultiPokemon
    name = details[0]
IndexError: tuple index out of range
```

It works as normal for single deck stats.

**Comment by cslayb** [comment]
Same error here but it only successfully works for a couple of my decks. Many of my single decks, and my collection deck stats all crash with this error.
