### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DoctorToBeIn23** [sivenchinniah/Pokemanki#17]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-20 11:54:59
Add-ons possibly involved: ⁨Pokemanki, Opening the same window multiple time⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 31, in cmd
  File "aqt/webview.py", line 97, in _onCmd
  File "aqt/webview.py", line 500, in _onBridgeCmd
  File "aqt/toolbar.py", line 154, in _linkHandler
  File "aqt/toolbar.py", line 175, in _statsLinkHandler
  File "aqt/main.py", line 1016, in onStats
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/354407385/__init__.py", line 60, in open
    return function(name, *args, **kwargs)
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/354407385/__init__.py", line 70, in openMany
    instance = creator(*args, **kwargs)
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-146>", line 2, in __init__
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 657, in repl
  File "aqt/stats.py", line 52, in __init__
  File "aqt/stats.py", line 97, in refresh
  File "anki/stats.py", line 125, in report
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-92>", line 2, in todayStats
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/633922407/tagmon.py", line 38, in tagmonDisplay
    tagmon = TagPokemon()
  File "/Users/Jacob/Library/Application Support/Anki2/addons21/633922407/tagmon.py", line 214, in TagPokemon
    if config['generation_1']:
KeyError: 'generation_1'

**Comment by WickedCheese18** [comment]
I'm having the same issue in 2.1.22:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-25 15:14:37

Caught exception:
Traceback (most recent call last):
  File "aqt\main.py", line 1016, in onStats
  File "aqt\__init__.py", line 93, in open
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-134>", line 2, in __init__
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 657, in repl
  File "aqt\stats.py", line 52, in __init__
  File "aqt\stats.py", line 97, in refresh
  File "lib\site-packages\anki\stats.py", line 131, in report
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-98>", line 2, in easeGraph
  File "lib\site-packages\anki\hooks.py", line 666, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 663, in repl
  File "C:\Users\lawso\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 38, in tagmonDisplay
    tagmon = TagPokemon()
  File "C:\Users\lawso\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 214, in TagPokemon
    if config['generation_1']:
KeyError: 'generation_1'
