### ISSUE TITLE
Error while opening the stats

### ISSUE THREAD

**Issue by henryford96** [sivenchinniah/Pokemanki#22]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-04-09 13:24:16

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 30, in cmd
  File "aqt\webview.py", line 96, in _onCmd
  File "aqt\webview.py", line 422, in _onBridgeCmd
  File "aqt\toolbar.py", line 75, in _linkHandler
  File "aqt\toolbar.py", line 96, in _statsLinkHandler
  File "aqt\main.py", line 1007, in onStats
  File "aqt\__init__.py", line 92, in open
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-58>", line 2, in __init__
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 521, in repl
  File "aqt\stats.py", line 52, in __init__
  File "aqt\stats.py", line 97, in refresh
  File "lib\site-packages\anki\stats.py", line 117, in report
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-48>", line 2, in todayStats
  File "lib\site-packages\anki\hooks.py", line 530, in decorator_wrapper
  File "lib\site-packages\anki\hooks.py", line 527, in repl
  File "C:\Users\Henry ford\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 38, in tagmonDisplay
    tagmon = TagPokemon()
  File "C:\Users\Henry ford\AppData\Roaming\Anki2\addons21\633922407\tagmon.py", line 214, in TagPokemon
    if config['generation_1']:
KeyError: 'generation_1'

**Comment by Rubyuniform1898** [comment]
Having the same issue. Add-on is not functional.

**Comment by santiagoesmeral** [comment]
Same here, seems to have problems with Tags. Decks work just fine
