### ISSUE TITLE
(ANKI 2.1.30 &2.1.36) Pokemon eggs (starter) not showing up under stats & trade window 

### ISSUE THREAD

**Issue by soradaihikari** [sivenchinniah/Pokemanki#36]
I apologize if I didn't install something correctly, I'm new to POKEANKI (started today).

- I downloaded my ANKI versions (2.1.30 and 2.1.36) from https://apps.ankiweb.net/downloads/archive/. 
- Regarding addons I only have the AMBOSS addon, POKEANKI addon, and the review heatmap addon. 
- I have installed POKEANKI via the "633922407" pokeanki addon code
- I have assigned my starter egg to my Reproductive Pathology deck that I was planning on working on
- I've finished about 100 cards to test the app and under my stats I do not see any pokemon nor eggs under the stats option :(

What am I doing wrong in my setup? :( 

The only error I am able to reproduce is by entering the "Trade" window under the POKEANKI toolbar:
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.36 (c505894b) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-02-24 16:32:43

Caught exception:
Traceback (most recent call last):
  File "C:\Users\SoraR\AppData\Roaming\Anki2\addons21\633922407\trades.py", line 237, in tradeFunction
    self.newTrades()
  File "C:\Users\SoraR\AppData\Roaming\Anki2\addons21\633922407\trades.py", line 161, in newTrades
    randno = random.randint(0, len(deckmonlist)-1)
  File "random.py", line 248, in randint
  File "random.py", line 226, in randrange
ValueError: empty range for randrange() (0, 0, 0)

**Comment by BlueGreenMagick** [comment]
I think if you will need to do more reviews for the pokemons to show up. Especially since you are probably using a massive deck. The pokemon levels are calculated with number of cards in deck in consideration, and the pokemons don't show up when they are below level 1.

The bug when clicking trade is a different one. The strange thing about this issue is that they seem to be using the tag mode, and yet still sees the trade menu. (The trade menu should not be visible for tag mode)
