### ISSUE TITLE
Error for starters " Tepig Oshawott Snivy"

### ISSUE THREAD

**Issue by lgddm** [sivenchinniah/Pokemanki#43]
When started Pokemanki, one of my decks triggered the starters " Tepig Oshawott Snivy" (I just donwloaded the add-on so I don't know well what any of this means :) 
However, Tepig and Oshawott were in the same choice (meaning the choices were "TepigO shawott" and "Snivy"). When I chose "TepigO shawott" the addon crashed and anki showed that "error popup that requests to restart anki pressing shift"

**Comment by khonkhortisan** [comment]
![image](https://user-images.githubusercontent.com/1996449/189312108-6185257c-4d74-47fe-9012-4d647259cd45.png)
```
Error 
Se ha producido un error. Por favor inicia la Anki manteniendo presionadas ples teclas Mayús y la flecha hacia abajo, lo que desactivará temporalmente los extensiones que tienes instaladas. 
Si este error persiste sólo cuando tienes las extensiones activadas, utiliza Herramientas > Menú de Extensiones para deshabilitar alguna extensión y reinicia el Anki, repitiendo este proceso hasta que descubras qué extensión en concreto es la que causa el problema 
Cuando hayas descubierto la extensión que causaba el problema, por favor informa de esto a [sitio de soporte de extensiones](https://forums.ankiweb.net/c/add-ons/11). 
Información de depuración: 
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-08 21:20:58

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\633922407\main.py", line 114, in message_handler
    html = pokemonDisplay(wholeCollection=True).replace("`", "'")
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\633922407\display.py", line 81, in pokemonDisplay
    multideckmon = MultiPokemon(wholeCollection=True)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Anki2\addons21\633922407\compute.py", line 338, in MultiPokemon
    idx = int(idx)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```
