### ISSUE TITLE
Pokemanki not working on Mac??

### ISSUE THREAD

**Issue by catherinesofie** [sivenchinniah/Pokemanki#48]
I have Anki version 2.1.35 and I have tried downloading and redownloading Pokemanki and even resetting it but I am never able to see my Pokemon on my stats page. When I download the add on I am offered the starter pokemon and assign it to a deck but then my stats page never loads for me to be able to see the egg. I also get messages when I "find a new Pokemon" but can never see the egg.

Basically, when I open my stats page, the application takes too long to load or doesn't respond to where I have to force quit Anki to be able to do anything. I can't even see the graphs at the bottom anymore.

Does anyone know if this may be a Mac problem or if there's a way to fix this?? I never get an error log so idk what's going on exactly.

**Comment by catherinesofie** [comment]
Also:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-19 17:41:11
Add-ons possibly involved: ⁨Pokemanki⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/catherinerothman/Library/Application Support/Anki2/addons21/633922407/trades.py", line 237, in tradeFunction
    self.newTrades()
  File "/Users/catherinerothman/Library/Application Support/Anki2/addons21/633922407/trades.py", line 161, in newTrades
    randno = random.randint(0, len(deckmonlist)-1)
  File "random.py", line 248, in randint
  File "random.py", line 226, in randrange
ValueError: empty range for randrange() (0, 0, 0)

**Comment by catherinesofie** [comment]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.1 Qt 5.9.7 PyQt 5.13.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-08-19 17:41:11
Add-ons possibly involved: ⁨Pokemanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 541, in _onBridgeCmd
  File "aqt/gui_hooks.py", line 2959, in __call__
  File "/Users/catherinerothman/Library/Application Support/Anki2/addons21/633922407/main.py", line 119, in message_handler
    statsDialog.form.web.eval("Pokemanki.setPokemanki(`{}`)".format(html))
AttributeError: 'NoneType' object has no attribute 'eval'
