### ISSUE TITLE
Getting error message when trying to choose a deck for my starter pokemon

### ISSUE THREAD

**Issue by C-C32** [sivenchinniah/Pokemanki#65]
Getting this error message: 
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.65 (aa9a734f) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
Platform: macOS-13.4-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-09-25 19:21:39
Add-ons possibly involved: ⁨Pokmanki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 46, in cmd
  File "aqt.webview", line 153, in _onCmd
  File "aqt.webview", line 656, in _onBridgeCmd
  File "_aqt.hooks", line 5255, in __call__
  File "/Users/----------------/Library/Application Support/Anki2/addons21/1041307953/main.py", line 136, in message_handler
    html = pokemon_display(f, False).replace("`", "'")
  File "/Users/----------------/Library/Application Support/Anki2/addons21/1041307953/display.py", line 48, in pokemon_display
    pokemon = MultiPokemon(wholecollection)
  File "/Users/----------------/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 317, in MultiPokemon
    FirstPokemon()
  File "/Users/----------------/Library/Application Support/Anki2/addons21/1041307953/compute.py", line 244, in FirstPokemon
    deckmon = msgbox.clickedButton().text()
AttributeError: 'NoneType' object has no attribute 'text'

Not sure if there's something wrong on my end or not.

**Comment by nchetla** [comment]
Add on hasn't been updated in long time, gonna have issues
